name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: "Build for Windows x64"
        run: GOOS=windows GOARCH=amd64 go build -o myapp-windows-x64.exe

      - name: "Build for Linux x64"
        run: GOOS=linux GOARCH=amd64 go build -o myapp-linux-x64

      - name: "Build for Linux ARM"
        run: GOOS=linux GOARCH=arm go build -o myapp-linux-arm

      - name: "Publish Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: myapp-artifacts
          path: |
            myapp-windows-x64.exe
            myapp-linux-x64
            myapp-linux-arm
