name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Rust Linux
        run: rustup target add arm-unknown-linux-gnueabihf

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Configure Cargo for ARM
        run: |
          mkdir -p .cargo
          echo '[target.arm-unknown-linux-gnueabihf]' >> .cargo/config.toml
          echo 'linker = "arm-linux-gnueabihf-gcc"' >> .cargo/config.toml

      - name: Build for Linux ARM
        run: |
          export CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
          cargo build --target arm-unknown-linux-gnueabihf

      - name: Build for Linux ARM
        run: cargo build --release --target arm-unknown-linux-gnueabihf

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rmt-turbo
          path: target/arm-unknown-linux-gnueabihf/release/rmt-turbo
