name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: "Build for Windows x64"
        run: GOOS=windows GOARCH=amd64 go build -o rtcn-windows-x64.exe

      - name: "Build for Linux x64"
        run: GOOS=linux GOARCH=amd64 go build -o rtcn-linux-x64

      - name: "Build for Linux ARM"
        run: GOOS=linux GOARCH=arm go build -o rtcn-linux-arm

      - name: "Publish Windows x64 Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: rtcn-windows-x64
          path: rtcn-windows-x64.exe

      - name: "Publish Linux x64 Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: rtcn-linux-x64
          path: rtcn-linux-x64

      - name: "Publish Linux ARM Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: rtcn-linux-arm
          path: rtcn-linux-arm
